/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AbstractProductA;

import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Milos
 */
public class MojPanel1 extends Panel {

    /**
     * Creates new form MojPanel1
     */
    public MojPanel1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtIdClanovi = new javax.swing.JTextField();
        jtxtIme = new javax.swing.JTextField();
        jtxtPrezime = new javax.swing.JTextField();
        jComboBoxPaket = new javax.swing.JComboBox<>();
        DatumDo = new datechooser.beans.DateChooserCombo();
        jbtnDodajClana = new javax.swing.JButton();
        jbtnIzmeni = new javax.swing.JButton();
        jbtnObrisi = new javax.swing.JButton();
        jbtnPronadji = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Poruka = new javax.swing.JTextField();

        setBackground(new java.awt.Color(228, 234, 234));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id Clana:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 27, 50, 23));

        jLabel2.setText("Ime:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 50, -1));

        jLabel3.setText("Prezime");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, 50, 20));

        jLabel4.setText("Paket:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, 40, 20));

        jLabel5.setText("Datum do:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 171, 60, 20));

        jtxtIdClanovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdClanoviActionPerformed(evt);
            }
        });
        add(jtxtIdClanovi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 60, 20));

        jtxtIme.setText(" ");
        add(jtxtIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 220, -1));
        add(jtxtPrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 220, -1));

        jComboBoxPaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "obicni", "bolji", "najbolji" }));
        add(jComboBoxPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 220, 20));
        add(DatumDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 220, -1));

        jbtnDodajClana.setText("Dodaj ");
        add(jbtnDodajClana, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, -1));

        jbtnIzmeni.setText(" Izmeni");
        add(jbtnIzmeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 80, -1));

        jbtnObrisi.setText("Obrisi");
        add(jbtnObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, -1));

        jbtnPronadji.setText("Pronadji");
        add(jbtnPronadji, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 27, 150, -1));

        jLabel6.setText("Poruka:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));

        Poruka.setForeground(new java.awt.Color(255, 0, 0));
        Poruka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorukaActionPerformed(evt);
            }
        });
        add(Poruka, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtIdClanoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdClanoviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdClanoviActionPerformed

    private void PorukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PorukaActionPerformed

    @Override
    public String getIdClanovi() {
        return jtxtIdClanovi.getText();
    }

    @Override
    public JTextField getIdClanovi1() {
        return jtxtIdClanovi;
    }

    @Override
    public String getIme() {
        return jtxtIme.getText();
    }

    @Override
    public String getPrezime() {
        return jtxtPrezime.getText();
    }

    @Override
    public String getPaket() {
        return jComboBoxPaket.getSelectedItem().toString();
    }

    @Override
    public Date getDatumDo() {
        return DatumDo.getSelectedDate().getTime();
    }

    @Override
    public void setIdClanovi(String IdClanovi1) {
        jtxtIdClanovi.setText(IdClanovi1);
    }

    @Override
    public void setIme(String ime) {
        jtxtIme.setText(ime);
    }
    

    @Override
    public void setPrezime(String prezime) {
        jtxtPrezime.setText(prezime);
    }

    @Override
    public void setPaket(String paket) {
        jComboBoxPaket.setSelectedItem(paket);
    }

    @Override
    public void setDatumDo(Date Datum1) {
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(Datum1);
        DatumDo.setSelectedDate(gc);
    }

    @Override
    public void setPoruka(String Poruka1) {
        Poruka.setText(Poruka1);
    }

    @Override
    public JButton getDodaj() {
        return jbtnDodajClana;
    }

    @Override
    public JButton getPromeni() {
        return jbtnIzmeni;
    }

    @Override
    public JButton getObrisi() {
        return jbtnObrisi;
    }

    @Override
    public JButton getNadji() {
        return jbtnPronadji;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo DatumDo;
    private javax.swing.JTextField Poruka;
    private javax.swing.JComboBox<String> jComboBoxPaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtnDodajClana;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JButton jbtnPronadji;
    private javax.swing.JTextField jtxtIdClanovi;
    private javax.swing.JTextField jtxtIme;
    private javax.swing.JTextField jtxtPrezime;
    // End of variables declaration//GEN-END:variables
}
